package auditd

// parseAuditLogsError is generated by the parseAuditLogs function.
type parseAuditLogsError struct {
	message string
	inner   error
}

func (o *parseAuditLogsError) Error() string {
	return o.message
}

func (o *parseAuditLogsError) Unwrap() error {
	return o.inner
}

// reassemblerCBError is generated by reassemblerCB.
type reassemblerCBError struct {
	message string
	inner   error
}

func (o *reassemblerCBError) Error() string {
	return o.message
}

func (o *reassemblerCBError) Unwrap() error {
	return o.inner
}
