FROM ubuntu:22.04
RUN apt update
RUN apt install rsyslog -y
RUN rm -r /etc/rsyslog.d && mkdir /etc/rsyslog.d
COPY config/rsyslog.d/* /etc/rsyslog.d/
COPY config/rsyslog.conf /etc/rsyslog.conf
ENTRYPOINT ["rsyslogd" ,"-n", "-d"]