FROM alpine:3.18.3
RUN apk update
RUN apk upgrade
RUN apk add rsyslog
RUN mkdir /etc/rsyslog.d
COPY config/rsyslog.d/* /etc/rsyslog.d/
COPY config/rsyslog.conf /etc/rsyslog.conf
ENTRYPOINT ["rsyslogd" ,"-n"]