// go run internal/auditd/gen-extra-map/main.go -only-ids -d Good -o auditd_good_metadata_test.go testdata/good
//
// Code generated by the command above. DO NOT EDIT.

package auditd

import (
	"testing"

	"github.com/elastic/go-libaudit/v2/aucoalesce"
)

// metadataForGoodAuditdEvents is an auto-generated function that returns
// the EventMetadata.Extra map found in the auditevent.AuditEvent object
// for the corresponding auditd event.
//
// i is the expected index of the auditevent.AuditEvent.
//
// Generated for test data files:
//   - testdata/good/00-login.txt
//   - testdata/good/01-ls-cwd.txt
//   - testdata/good/02-cat-resolv-conf.txt
//   - testdata/good/03-ls-slash-root.txt
//   - testdata/good/04-logout.txt
//   - testdata/good/05-unrelated.txt
func metadataForGoodAuditdEvents(i int, t *testing.T) map[string]interface{}{
	var extra map[string]interface{}

	switch i {
	case 0:
		// auditd sequence number: 30166
		extra = map[string]interface{}{
			"action": "changed-login-id-to",
			"how":    "",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "1000",
				Secondary: "",
			},
		}
	case 1:
		// auditd sequence number: 30166
		extra = map[string]interface{}{
			"action": "wrote-to-file",
			"how":    "/usr/sbin/sshd",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "",
				Secondary: "",
			},
		}
	case 2:
		// auditd sequence number: 30167
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/bin/sh",
				Secondary: "",
			},
		}
	case 3:
		// auditd sequence number: 30168
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/env",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/env",
				Secondary: "",
			},
		}
	case 4:
		// auditd sequence number: 30169
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/env",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/sbin/run-parts",
				Secondary: "",
			},
		}
	case 5:
		// auditd sequence number: 30170
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/env",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/bin/run-parts",
				Secondary: "",
			},
		}
	case 6:
		// auditd sequence number: 30171
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/env",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/sbin/run-parts",
				Secondary: "",
			},
		}
	case 7:
		// auditd sequence number: 30172
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/run-parts",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/run-parts",
				Secondary: "",
			},
		}
	case 8:
		// auditd sequence number: 30173
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/00-header",
				Secondary: "",
			},
		}
	case 9:
		// auditd sequence number: 30174
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/uname",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/uname",
				Secondary: "",
			},
		}
	case 10:
		// auditd sequence number: 30175
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/uname",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/uname",
				Secondary: "",
			},
		}
	case 11:
		// auditd sequence number: 30176
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/uname",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/uname",
				Secondary: "",
			},
		}
	case 12:
		// auditd sequence number: 30177
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/10-help-text",
				Secondary: "",
			},
		}
	case 13:
		// auditd sequence number: 30178
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/50-landscape-sysinfo",
				Secondary: "",
			},
		}
	case 14:
		// auditd sequence number: 30179
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 15:
		// auditd sequence number: 30180
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 16:
		// auditd sequence number: 30181
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/bc",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/bc",
				Secondary: "",
			},
		}
	case 17:
		// auditd sequence number: 30182
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/date",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/bin/date",
				Secondary: "",
			},
		}
	case 18:
		// auditd sequence number: 30183
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/landscape-sysinfo",
				Secondary: "",
			},
		}
	case 19:
		// auditd sequence number: 30184
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/sbin/uname",
				Secondary: "",
			},
		}
	case 20:
		// auditd sequence number: 30185
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/bin/uname",
				Secondary: "",
			},
		}
	case 21:
		// auditd sequence number: 30186
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/sbin/uname",
				Secondary: "",
			},
		}
	case 22:
		// auditd sequence number: 30187
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/uname",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/uname",
				Secondary: "",
			},
		}
	case 23:
		// auditd sequence number: 30188
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/lib/ssl/openssl.cnf",
				Secondary: "",
			},
		}
	case 24:
		// auditd sequence number: 30189
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/sbin/who",
				Secondary: "",
			},
		}
	case 25:
		// auditd sequence number: 30190
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/bin/who",
				Secondary: "",
			},
		}
	case 26:
		// auditd sequence number: 30191
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "landscape-sysin",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/sbin/who",
				Secondary: "",
			},
		}
	case 27:
		// auditd sequence number: 30192
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/who",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/who",
				Secondary: "",
			},
		}
	case 28:
		// auditd sequence number: 30193
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/50-motd-news",
				Secondary: "",
			},
		}
	case 29:
		// auditd sequence number: 30194
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/head",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/head",
				Secondary: "",
			},
		}
	case 30:
		// auditd sequence number: 30195
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/tr",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/tr",
				Secondary: "",
			},
		}
	case 31:
		// auditd sequence number: 30196
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 32:
		// auditd sequence number: 30197
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cat",
				Secondary: "",
			},
		}
	case 33:
		// auditd sequence number: 30198
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/85-fwupd",
				Secondary: "",
			},
		}
	case 34:
		// auditd sequence number: 30199
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/88-esm-announce",
				Secondary: "",
			},
		}
	case 35:
		// auditd sequence number: 30200
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/90-updates-available",
				Secondary: "",
			},
		}
	case 36:
		// auditd sequence number: 30201
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cat",
				Secondary: "",
			},
		}
	case 37:
		// auditd sequence number: 30202
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 38:
		// auditd sequence number: 30203
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/find",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/find",
				Secondary: "",
			},
		}
	case 39:
		// auditd sequence number: 30204
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/91-contract-ua-esm-status",
				Secondary: "",
			},
		}
	case 40:
		// auditd sequence number: 30205
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/91-release-upgrade",
				Secondary: "",
			},
		}
	case 41:
		// auditd sequence number: 30206
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "lsb_release",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/lsb_release",
				Secondary: "",
			},
		}
	case 42:
		// auditd sequence number: 30207
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 43:
		// auditd sequence number: 30208
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/id",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/id",
				Secondary: "",
			},
		}
	case 44:
		// auditd sequence number: 30209
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/lib/ubuntu-release-upgrader/release-upgrade-motd",
				Secondary: "",
			},
		}
	case 45:
		// auditd sequence number: 30210
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/date",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/date",
				Secondary: "",
			},
		}
	case 46:
		// auditd sequence number: 30211
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/stat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/stat",
				Secondary: "",
			},
		}
	case 47:
		// auditd sequence number: 30212
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/expr",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/expr",
				Secondary: "",
			},
		}
	case 48:
		// auditd sequence number: 30213
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cat",
				Secondary: "",
			},
		}
	case 49:
		// auditd sequence number: 30214
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/92-unattended-upgrades",
				Secondary: "",
			},
		}
	case 50:
		// auditd sequence number: 30215
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/share/unattended-upgrades/update-motd-unattended-upgrades",
				Secondary: "",
			},
		}
	case 51:
		// auditd sequence number: 30216
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/95-hwe-eol",
				Secondary: "",
			},
		}
	case 52:
		// auditd sequence number: 30217
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/lib/update-notifier/update-motd-hwe-eol",
				Secondary: "",
			},
		}
	case 53:
		// auditd sequence number: 30218
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/systemd-detect-virt",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/systemd-detect-virt",
				Secondary: "",
			},
		}
	case 54:
		// auditd sequence number: 30219
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/apt-config",
				Secondary: "",
			},
		}
	case 55:
		// auditd sequence number: 30220
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/",
				Secondary: "",
			},
		}
	case 56:
		// auditd sequence number: 30221
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01-vendor-ubuntu",
				Secondary: "",
			},
		}
	case 57:
		// auditd sequence number: 30222
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove",
				Secondary: "",
			},
		}
	case 58:
		// auditd sequence number: 30223
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove-postgresql",
				Secondary: "",
			},
		}
	case 59:
		// auditd sequence number: 30224
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/10periodic",
				Secondary: "",
			},
		}
	case 60:
		// auditd sequence number: 30225
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/15update-stamp",
				Secondary: "",
			},
		}
	case 61:
		// auditd sequence number: 30226
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20apt-esm-hook.conf",
				Secondary: "",
			},
		}
	case 62:
		// auditd sequence number: 30227
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20archive",
				Secondary: "",
			},
		}
	case 63:
		// auditd sequence number: 30228
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20auto-upgrades",
				Secondary: "",
			},
		}
	case 64:
		// auditd sequence number: 30229
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20packagekit",
				Secondary: "",
			},
		}
	case 65:
		// auditd sequence number: 30230
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20snapd.conf",
				Secondary: "",
			},
		}
	case 66:
		// auditd sequence number: 30231
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50command-not-found",
				Secondary: "",
			},
		}
	case 67:
		// auditd sequence number: 30232
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50unattended-upgrades",
				Secondary: "",
			},
		}
	case 68:
		// auditd sequence number: 30233
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/70debconf",
				Secondary: "",
			},
		}
	case 69:
		// auditd sequence number: 30234
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/99update-notifier",
				Secondary: "",
			},
		}
	case 70:
		// auditd sequence number: 30235
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dpkg",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dpkg",
				Secondary: "",
			},
		}
	case 71:
		// auditd sequence number: 30236
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/apt-config",
				Secondary: "",
			},
		}
	case 72:
		// auditd sequence number: 30237
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/",
				Secondary: "",
			},
		}
	case 73:
		// auditd sequence number: 30238
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01-vendor-ubuntu",
				Secondary: "",
			},
		}
	case 74:
		// auditd sequence number: 30239
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove",
				Secondary: "",
			},
		}
	case 75:
		// auditd sequence number: 30240
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove-postgresql",
				Secondary: "",
			},
		}
	case 76:
		// auditd sequence number: 30241
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/10periodic",
				Secondary: "",
			},
		}
	case 77:
		// auditd sequence number: 30242
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/15update-stamp",
				Secondary: "",
			},
		}
	case 78:
		// auditd sequence number: 30243
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20apt-esm-hook.conf",
				Secondary: "",
			},
		}
	case 79:
		// auditd sequence number: 30244
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20archive",
				Secondary: "",
			},
		}
	case 80:
		// auditd sequence number: 30245
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20auto-upgrades",
				Secondary: "",
			},
		}
	case 81:
		// auditd sequence number: 30246
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20packagekit",
				Secondary: "",
			},
		}
	case 82:
		// auditd sequence number: 30247
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20snapd.conf",
				Secondary: "",
			},
		}
	case 83:
		// auditd sequence number: 30248
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50command-not-found",
				Secondary: "",
			},
		}
	case 84:
		// auditd sequence number: 30249
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50unattended-upgrades",
				Secondary: "",
			},
		}
	case 85:
		// auditd sequence number: 30250
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/70debconf",
				Secondary: "",
			},
		}
	case 86:
		// auditd sequence number: 30251
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/99update-notifier",
				Secondary: "",
			},
		}
	case 87:
		// auditd sequence number: 30252
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dpkg",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dpkg",
				Secondary: "",
			},
		}
	case 88:
		// auditd sequence number: 30253
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/apt-config",
				Secondary: "",
			},
		}
	case 89:
		// auditd sequence number: 30254
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/",
				Secondary: "",
			},
		}
	case 90:
		// auditd sequence number: 30255
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01-vendor-ubuntu",
				Secondary: "",
			},
		}
	case 91:
		// auditd sequence number: 30256
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove",
				Secondary: "",
			},
		}
	case 92:
		// auditd sequence number: 30257
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove-postgresql",
				Secondary: "",
			},
		}
	case 93:
		// auditd sequence number: 30258
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/10periodic",
				Secondary: "",
			},
		}
	case 94:
		// auditd sequence number: 30259
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/15update-stamp",
				Secondary: "",
			},
		}
	case 95:
		// auditd sequence number: 30260
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20apt-esm-hook.conf",
				Secondary: "",
			},
		}
	case 96:
		// auditd sequence number: 30261
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20archive",
				Secondary: "",
			},
		}
	case 97:
		// auditd sequence number: 30262
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20auto-upgrades",
				Secondary: "",
			},
		}
	case 98:
		// auditd sequence number: 30263
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20packagekit",
				Secondary: "",
			},
		}
	case 99:
		// auditd sequence number: 30264
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20snapd.conf",
				Secondary: "",
			},
		}
	case 100:
		// auditd sequence number: 30265
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50command-not-found",
				Secondary: "",
			},
		}
	case 101:
		// auditd sequence number: 30266
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50unattended-upgrades",
				Secondary: "",
			},
		}
	case 102:
		// auditd sequence number: 30267
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/70debconf",
				Secondary: "",
			},
		}
	case 103:
		// auditd sequence number: 30268
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/99update-notifier",
				Secondary: "",
			},
		}
	case 104:
		// auditd sequence number: 30269
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dpkg",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dpkg",
				Secondary: "",
			},
		}
	case 105:
		// auditd sequence number: 30270
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/apt-config",
				Secondary: "",
			},
		}
	case 106:
		// auditd sequence number: 30271
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/",
				Secondary: "",
			},
		}
	case 107:
		// auditd sequence number: 30272
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01-vendor-ubuntu",
				Secondary: "",
			},
		}
	case 108:
		// auditd sequence number: 30273
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove",
				Secondary: "",
			},
		}
	case 109:
		// auditd sequence number: 30274
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove-postgresql",
				Secondary: "",
			},
		}
	case 110:
		// auditd sequence number: 30275
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/10periodic",
				Secondary: "",
			},
		}
	case 111:
		// auditd sequence number: 30276
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/15update-stamp",
				Secondary: "",
			},
		}
	case 112:
		// auditd sequence number: 30277
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20apt-esm-hook.conf",
				Secondary: "",
			},
		}
	case 113:
		// auditd sequence number: 30278
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20archive",
				Secondary: "",
			},
		}
	case 114:
		// auditd sequence number: 30279
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20auto-upgrades",
				Secondary: "",
			},
		}
	case 115:
		// auditd sequence number: 30280
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20packagekit",
				Secondary: "",
			},
		}
	case 116:
		// auditd sequence number: 30281
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20snapd.conf",
				Secondary: "",
			},
		}
	case 117:
		// auditd sequence number: 30282
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50command-not-found",
				Secondary: "",
			},
		}
	case 118:
		// auditd sequence number: 30283
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50unattended-upgrades",
				Secondary: "",
			},
		}
	case 119:
		// auditd sequence number: 30284
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/70debconf",
				Secondary: "",
			},
		}
	case 120:
		// auditd sequence number: 30285
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/99update-notifier",
				Secondary: "",
			},
		}
	case 121:
		// auditd sequence number: 30286
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dpkg",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dpkg",
				Secondary: "",
			},
		}
	case 122:
		// auditd sequence number: 30287
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/apt-config",
				Secondary: "",
			},
		}
	case 123:
		// auditd sequence number: 30288
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/",
				Secondary: "",
			},
		}
	case 124:
		// auditd sequence number: 30289
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01-vendor-ubuntu",
				Secondary: "",
			},
		}
	case 125:
		// auditd sequence number: 30290
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove",
				Secondary: "",
			},
		}
	case 126:
		// auditd sequence number: 30291
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/01autoremove-postgresql",
				Secondary: "",
			},
		}
	case 127:
		// auditd sequence number: 30292
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/10periodic",
				Secondary: "",
			},
		}
	case 128:
		// auditd sequence number: 30293
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/15update-stamp",
				Secondary: "",
			},
		}
	case 129:
		// auditd sequence number: 30294
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20apt-esm-hook.conf",
				Secondary: "",
			},
		}
	case 130:
		// auditd sequence number: 30295
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20archive",
				Secondary: "",
			},
		}
	case 131:
		// auditd sequence number: 30296
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20auto-upgrades",
				Secondary: "",
			},
		}
	case 132:
		// auditd sequence number: 30297
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20packagekit",
				Secondary: "",
			},
		}
	case 133:
		// auditd sequence number: 30298
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/20snapd.conf",
				Secondary: "",
			},
		}
	case 134:
		// auditd sequence number: 30299
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50command-not-found",
				Secondary: "",
			},
		}
	case 135:
		// auditd sequence number: 30300
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/50unattended-upgrades",
				Secondary: "",
			},
		}
	case 136:
		// auditd sequence number: 30301
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/70debconf",
				Secondary: "",
			},
		}
	case 137:
		// auditd sequence number: 30302
		extra = map[string]interface{}{
			"action": "opened-file",
			"how":    "/usr/bin/apt-config",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/apt/apt.conf.d/99update-notifier",
				Secondary: "",
			},
		}
	case 138:
		// auditd sequence number: 30303
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dpkg",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dpkg",
				Secondary: "",
			},
		}
	case 139:
		// auditd sequence number: 30304
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/find",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/find",
				Secondary: "",
			},
		}
	case 140:
		// auditd sequence number: 30305
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/id",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/id",
				Secondary: "",
			},
		}
	case 141:
		// auditd sequence number: 30306
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dirname",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dirname",
				Secondary: "",
			},
		}
	case 142:
		// auditd sequence number: 30307
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/mktemp",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/mktemp",
				Secondary: "",
			},
		}
	case 143:
		// auditd sequence number: 30308
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cat",
				Secondary: "",
			},
		}
	case 144:
		// auditd sequence number: 30309
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/rm",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/rm",
				Secondary: "",
			},
		}
	case 145:
		// auditd sequence number: 30310
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/97-overlayroot",
				Secondary: "",
			},
		}
	case 146:
		// auditd sequence number: 30311
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/egrep",
				Secondary: "",
			},
		}
	case 147:
		// auditd sequence number: 30312
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/sbin/grep",
				Secondary: "",
			},
		}
	case 148:
		// auditd sequence number: 30313
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/sort",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/sort",
				Secondary: "",
			},
		}
	case 149:
		// auditd sequence number: 30314
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/local/bin/grep",
				Secondary: "",
			},
		}
	case 150:
		// auditd sequence number: 30315
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/sbin/grep",
				Secondary: "",
			},
		}
	case 151:
		// auditd sequence number: 30316
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 152:
		// auditd sequence number: 30317
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/98-fsck-at-reboot",
				Secondary: "",
			},
		}
	case 153:
		// auditd sequence number: 30318
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/lib/update-notifier/update-motd-fsck-at-reboot",
				Secondary: "",
			},
		}
	case 154:
		// auditd sequence number: 30319
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/id",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/id",
				Secondary: "",
			},
		}
	case 155:
		// auditd sequence number: 30320
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/stat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/stat",
				Secondary: "",
			},
		}
	case 156:
		// auditd sequence number: 30321
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/gawk",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/awk",
				Secondary: "",
			},
		}
	case 157:
		// auditd sequence number: 30322
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/date",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/date",
				Secondary: "",
			},
		}
	case 158:
		// auditd sequence number: 30323
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/date",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/date",
				Secondary: "",
			},
		}
	case 159:
		// auditd sequence number: 30324
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/mount",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/mount",
				Secondary: "",
			},
		}
	case 160:
		// auditd sequence number: 30325
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/gawk",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/awk",
				Secondary: "",
			},
		}
	case 161:
		// auditd sequence number: 30326
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/sbin/dumpe2fs",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/sbin/dumpe2fs",
				Secondary: "",
			},
		}
	case 162:
		// auditd sequence number: 30327
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 163:
		// auditd sequence number: 30328
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 164:
		// auditd sequence number: 30329
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 165:
		// auditd sequence number: 30330
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 166:
		// auditd sequence number: 30331
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 167:
		// auditd sequence number: 30332
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 168:
		// auditd sequence number: 30333
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 169:
		// auditd sequence number: 30334
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 170:
		// auditd sequence number: 30335
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 171:
		// auditd sequence number: 30336
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/date",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/date",
				Secondary: "",
			},
		}
	case 172:
		// auditd sequence number: 30337
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/sbin/dumpe2fs",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/sbin/dumpe2fs",
				Secondary: "",
			},
		}
	case 173:
		// auditd sequence number: 30338
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 174:
		// auditd sequence number: 30339
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 175:
		// auditd sequence number: 30340
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 176:
		// auditd sequence number: 30341
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 177:
		// auditd sequence number: 30342
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 178:
		// auditd sequence number: 30343
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 179:
		// auditd sequence number: 30344
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 180:
		// auditd sequence number: 30345
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/grep",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/grep",
				Secondary: "",
			},
		}
	case 181:
		// auditd sequence number: 30346
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cut",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cut",
				Secondary: "",
			},
		}
	case 182:
		// auditd sequence number: 30347
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/date",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/date",
				Secondary: "",
			},
		}
	case 183:
		// auditd sequence number: 30348
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cat",
				Secondary: "",
			},
		}
	case 184:
		// auditd sequence number: 30349
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/etc/update-motd.d/98-reboot-required",
				Secondary: "",
			},
		}
	case 185:
		// auditd sequence number: 30350
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/lib/update-notifier/update-motd-reboot-required",
				Secondary: "",
			},
		}
	case 186:
		// auditd sequence number: 30351
		extra = map[string]interface{}{
			"action": "started-session",
			"how":    "/usr/sbin/sshd",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "ssh",
				Secondary: "127.0.0.1",
			},
		}
	case 187:
		// auditd sequence number: 30352
		extra = map[string]interface{}{
			"action": "acquired-credentials",
			"how":    "/usr/sbin/sshd",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "ssh",
				Secondary: "127.0.0.1",
			},
		}
	case 188:
		// auditd sequence number: 30353
		extra = map[string]interface{}{
			"action": "logged-in",
			"how":    "/usr/sbin/sshd",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "/dev/pts/3",
				Secondary: "127.0.0.1",
			},
		}
	case 189:
		// auditd sequence number: 30354
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "bash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/bin/bash",
				Secondary: "",
			},
		}
	case 190:
		// auditd sequence number: 30355
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/locale-check",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/locale-check",
				Secondary: "",
			},
		}
	case 191:
		// auditd sequence number: 30356
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/locale",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/locale",
				Secondary: "",
			},
		}
	case 192:
		// auditd sequence number: 30357
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dash",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/lesspipe",
				Secondary: "",
			},
		}
	case 193:
		// auditd sequence number: 30358
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/basename",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/basename",
				Secondary: "",
			},
		}
	case 194:
		// auditd sequence number: 30359
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dirname",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dirname",
				Secondary: "",
			},
		}
	case 195:
		// auditd sequence number: 30360
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/dircolors",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/dircolors",
				Secondary: "",
			},
		}
	case 196:
		// auditd sequence number: 30361
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/ls",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/ls",
				Secondary: "",
			},
		}
	case 197:
		// auditd sequence number: 30362
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/cat",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/cat",
				Secondary: "",
			},
		}
	case 198:
		// auditd sequence number: 30363
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/ls",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/ls",
				Secondary: "",
			},
		}
	case 199:
		// auditd sequence number: 30364
		extra = map[string]interface{}{
			"action": "executed",
			"how":    "/usr/bin/clear_console",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "/usr/bin/clear_console",
				Secondary: "",
			},
		}
	case 200:
		// auditd sequence number: 30365
		extra = map[string]interface{}{
			"action": "ended-session",
			"how":    "/usr/sbin/sshd",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "ssh",
				Secondary: "127.0.0.1",
			},
		}
	case 201:
		// auditd sequence number: 30366
		extra = map[string]interface{}{
			"action": "disposed-credentials",
			"how":    "/usr/sbin/sshd",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "ssh",
				Secondary: "127.0.0.1",
			},
		}
	case 202:
		// auditd sequence number: 29923
		extra = map[string]interface{}{
			"action": "changed-login-id-to",
			"how":    "",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "0",
				Secondary: "",
			},
		}
	case 203:
		// auditd sequence number: 29923
		extra = map[string]interface{}{
			"action": "wrote-to-file",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "",
				Secondary: "",
			},
		}
	case 204:
		// auditd sequence number: 29924
		extra = map[string]interface{}{
			"action": "started-session",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 205:
		// auditd sequence number: 29925
		extra = map[string]interface{}{
			"action": "disposed-credentials",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 206:
		// auditd sequence number: 29926
		extra = map[string]interface{}{
			"action": "ended-session",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 207:
		// auditd sequence number: 29929
		extra = map[string]interface{}{
			"action": "changed-login-id-to",
			"how":    "",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "0",
				Secondary: "",
			},
		}
	case 208:
		// auditd sequence number: 29929
		extra = map[string]interface{}{
			"action": "wrote-to-file",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "",
				Secondary: "",
			},
		}
	case 209:
		// auditd sequence number: 29930
		extra = map[string]interface{}{
			"action": "started-session",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 210:
		// auditd sequence number: 29931
		extra = map[string]interface{}{
			"action": "disposed-credentials",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 211:
		// auditd sequence number: 29932
		extra = map[string]interface{}{
			"action": "ended-session",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 212:
		// auditd sequence number: 29935
		extra = map[string]interface{}{
			"action": "changed-login-id-to",
			"how":    "",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "0",
				Secondary: "",
			},
		}
	case 213:
		// auditd sequence number: 29935
		extra = map[string]interface{}{
			"action": "wrote-to-file",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "file",
				Primary:   "",
				Secondary: "",
			},
		}
	case 214:
		// auditd sequence number: 29936
		extra = map[string]interface{}{
			"action": "started-session",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 215:
		// auditd sequence number: 29937
		extra = map[string]interface{}{
			"action": "disposed-credentials",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	case 216:
		// auditd sequence number: 29938
		extra = map[string]interface{}{
			"action": "ended-session",
			"how":    "/usr/sbin/cron",
			"object": aucoalesce.Object{
				Type:      "user-session",
				Primary:   "cron",
				Secondary: "",
			},
		}
	default:
		t.Fatalf("got unknown event index %d", i)
	}

	return extra
}
