name: Executes integration tests
on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.5'
      - name: Execute tests
        run: |
          sudo apt update
          sudo apt install -y make rsyslog
          sudo cp contrib/rsyslog/config/rsyslog.conf /etc/rsyslog.conf
          sudo rm -rf /etc/rsyslog.d
          sudo mkdir /etc/rsyslog.d
          sudo cp -r contrib/rsyslog/config/rsyslog.d/* /etc/rsyslog.d/
          sudo mkdir -p /var/log/audito-maldito
          sudo mkdir -p /app-audit
          sudo mkfifo /app-audit/app-events-output-test.log
          sudo mkfifo /app-audit/sshd-pipe
          sudo mkfifo /app-audit/audit-pipe
          sudo systemctl restart rsyslog
          sudo make integration-test
          