name: Executes integration tests
on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.5'
      - name: Execute tests
        run: |
          sudo apt update
          sudo apt install -y make gcc curl libsystemd-dev
          sudo make integration-test
