---
name: test

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    env:
      GOPROXY: https://proxy.golang.org,direct
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora-minimal:40
    steps:
      - name: Install dependencies
        run: |
          microdnf install -y golang systemd-devel tar git

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run golangci-lint
        run: make lint

      - name: Run go tests and generate coverage report
        run: make coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ghcr.io/metal-toolbox/audito-maldito:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/metal-toolbox/audito-maldito:latest
          security-checks: 'vuln,config,secret'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-img-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-img-results.sarif'

      - name: Inspect action SARIF report
        run: cat 'trivy-img-results.sarif'

  repo-scan:
    name: repo-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          security-checks: 'vuln,config,secret'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-repo-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-repo-results.sarif'

      - name: Inspect action SARIF report
        run: cat 'trivy-repo-results.sarif'